services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle install &&bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
  db:
    image: mysql:8.0.32
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - mysql:/var/lib/mysql
    tty: true
    stdin_open: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
volumes:
  mysql:
  bundle:
